---

- name: Deleting pub-key from host
  hosts: "{{ servers }}"
  remote_user: "{{ user }}"
  gather_facts: False

  tasks:
    - name: Deleting of the key of the user from selected servers
      authorized_key:
        user: "{{ user }}"
        state: absent
        key: "{{ key }}"
